services:
  api:
    build: .
    container_name: telegram_service_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - stt_network
    volumes:
      - .:/code

  database:
    image: postgres:16.4
    container_name: telegram_service_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_RO_USER_PASSWORD=${POSTGRES_RO_USER_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stt_network

  redis:
    image: redis:7
    container_name: telegram_service_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - stt_network

  worker:
    build: .
    container_name: telegram_service_worker
    command: celery -A src.core.celery_app.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - api
      - redis
      - database
    volumes:
      - .:/code
    networks:
      - stt_network

  beat:
    build: .
    container_name: telegram_service_beat
    command: celery -A src.core.celery_app.celery beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - api
      - redis
      - database
    volumes:
      - .:/code
    networks:
      - stt_network

volumes:
  pgdata:
networks:
  stt_network:
    driver: bridge